remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Blog Personal de Erick
author: Erick Kramer
description: Blog personal para compartir información relacionada a desarrollo de software para robótica
  # theme: minima
google_analytics:
theme: jekyll-theme-hacker
